// <auto-generated />
using System;
using DCO.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DCO.DataAcces.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DCO.Dominio.Entidades.DCO_Barrio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificado")
                        .HasColumnType("datetime");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId", "Codigo")
                        .IsUnique();

                    b.ToTable("DCO_Barrio");
                });

            modelBuilder.Entity("DCO.Dominio.Entidades.DCO_ColaSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMensaje")
                        .HasColumnType("Text")
                        .HasComment("Detalle de error de procasado de la solicitud.");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasComment("Estado del proceso de la solicitud. (0: Pendiente, 1: Procesando, 2: Exitosa, 3: Fallida).");

                    b.Property<DateTime>("FechaCreado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaUltimoIntento")
                        .HasColumnType("datetime");

                    b.Property<int>("Intentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Intentos del proceso");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("Text")
                        .HasComment("Payload para la solicitud.");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasComment("Tipo de solicitud a realizar.");

                    b.Property<string>("UrlDestino")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasComment("Url destino para la cual se publica el evento.");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("Tipo");

                    b.ToTable("DCO_ColaSolicitudes");
                });

            modelBuilder.Entity("DCO.Dominio.Entidades.DCO_DatoConstante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificado")
                        .HasColumnType("datetime");

                    b.Property<int>("ListaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ListaId");

                    b.ToTable("DCO_DatosConstantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "CAUSAEXTERNAANEXO2",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4007),
                            ListaId = 2,
                            Nombre = "CAUSAS EXTERNAS DE CONSULTA PARA ANEXO 2",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "TIPOIDENTIANEXO",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4009),
                            ListaId = 9,
                            Nombre = "TIPOS DE IDENTIFICACIÓN PARA REGISTRO DE ANEXOS TÉCNICOS A PACIENTES",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "TIPOIDENTIEMPRESA",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4011),
                            ListaId = 9,
                            Nombre = "TIPOS DE IDENTIFICACION PARA REGISTRO DE EMPRESAS",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "TIPOIDENTIREGISTROUSUARIO",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4013),
                            ListaId = 9,
                            Nombre = "TIPOS DE IDENTIFICACIÓN PARA REGISTRO DE USUARIOS DE APLICACIÓN",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "TIPOREGIMENANEXO2",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4015),
                            ListaId = 10,
                            Nombre = "TIPOS DE REGIMEN DISPONIBLES PARA ANEXO 2",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "TIPOREGIMENANEXO3",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4017),
                            ListaId = 10,
                            Nombre = "TIPOS DE REGIMEN DISPONIBLES PARA ANEXO 3",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "TIPOREGIMENANEXO9",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4019),
                            ListaId = 10,
                            Nombre = "TIPOS DE REGIMEN DISPONIBLES PARA ANEXO 9",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "TRIAGEANEXO2",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4021),
                            ListaId = 11,
                            Nombre = "NIVELES DE TRIAGE PARA EL ANEXO 2",
                            UsuarioCreadorId = 1
                        });
                });

            modelBuilder.Entity("DCO.Dominio.Entidades.DCO_DatoConstanteDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatoConstanteId")
                        .HasColumnType("int");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificado")
                        .HasColumnType("datetime");

                    b.Property<int>("ListaDetalleId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ListaDetalleId");

                    b.HasIndex("DatoConstanteId", "ListaDetalleId")
                        .IsUnique();

                    b.ToTable("DCO_DatosConstantesDetalles");
                });

            modelBuilder.Entity("DCO.Dominio.Entidades.DCO_Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificado")
                        .HasColumnType("datetime");

                    b.Property<short>("Indicativo")
                        .HasColumnType("smallint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaisId", "Codigo")
                        .IsUnique();

                    b.ToTable("DCO_Departamento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "05",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4080),
                            Indicativo = (short)4,
                            Nombre = "ANTIOQUIA",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "08",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4083),
                            Indicativo = (short)5,
                            Nombre = "ATLANTICO",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "11",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4084),
                            Indicativo = (short)1,
                            Nombre = "BOGOTA",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "13",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4086),
                            Indicativo = (short)5,
                            Nombre = "BOLIVAR",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "15",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4120),
                            Indicativo = (short)8,
                            Nombre = "BOYACA",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "17",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4122),
                            Indicativo = (short)6,
                            Nombre = "CALDAS",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "18",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4124),
                            Indicativo = (short)8,
                            Nombre = "CAQUETA",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "19",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4126),
                            Indicativo = (short)2,
                            Nombre = "CAUCA",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "20",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4128),
                            Indicativo = (short)5,
                            Nombre = "CESAR",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "23",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4130),
                            Indicativo = (short)4,
                            Nombre = "CORDOBA",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 11,
                            Codigo = "25",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4132),
                            Indicativo = (short)1,
                            Nombre = "CUNDINAMARCA",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 12,
                            Codigo = "27",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4134),
                            Indicativo = (short)4,
                            Nombre = "CHOCO",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 13,
                            Codigo = "41",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4136),
                            Indicativo = (short)8,
                            Nombre = "HUILA",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 14,
                            Codigo = "44",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4137),
                            Indicativo = (short)5,
                            Nombre = "LA GUAJIRA",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 15,
                            Codigo = "47",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4139),
                            Indicativo = (short)5,
                            Nombre = "MAGDALENA",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 16,
                            Codigo = "50",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4141),
                            Indicativo = (short)8,
                            Nombre = "META",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 17,
                            Codigo = "52",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4143),
                            Indicativo = (short)2,
                            Nombre = "NARIÑO",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 18,
                            Codigo = "54",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4145),
                            Indicativo = (short)7,
                            Nombre = "N. DE SANTANDER",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 19,
                            Codigo = "63",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4146),
                            Indicativo = (short)6,
                            Nombre = "QUINDIO",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 20,
                            Codigo = "66",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4148),
                            Indicativo = (short)6,
                            Nombre = "RISARALDA",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 21,
                            Codigo = "68",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4150),
                            Indicativo = (short)7,
                            Nombre = "SANTANDER",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 22,
                            Codigo = "70",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4152),
                            Indicativo = (short)5,
                            Nombre = "SUCRE",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 23,
                            Codigo = "73",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4154),
                            Indicativo = (short)8,
                            Nombre = "TOLIMA",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 24,
                            Codigo = "76",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4155),
                            Indicativo = (short)2,
                            Nombre = "VALLE DEL CAUCA",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 25,
                            Codigo = "81",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4157),
                            Indicativo = (short)7,
                            Nombre = "ARAUCA",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 26,
                            Codigo = "85",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4159),
                            Indicativo = (short)8,
                            Nombre = "CASANARE",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 27,
                            Codigo = "86",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4161),
                            Indicativo = (short)8,
                            Nombre = "PUTUMAYO",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 28,
                            Codigo = "88",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4163),
                            Indicativo = (short)8,
                            Nombre = "SAN ANDRES",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 29,
                            Codigo = "91",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4164),
                            Indicativo = (short)8,
                            Nombre = "AMAZONAS",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 30,
                            Codigo = "94",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4166),
                            Indicativo = (short)8,
                            Nombre = "GUAINIA",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 31,
                            Codigo = "95",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4168),
                            Indicativo = (short)8,
                            Nombre = "GUAVIARE",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 32,
                            Codigo = "97",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4170),
                            Indicativo = (short)8,
                            Nombre = "VAUPES",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 33,
                            Codigo = "98",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4172),
                            Indicativo = (short)0,
                            Nombre = "EXTRANJERO",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 34,
                            Codigo = "99",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4173),
                            Indicativo = (short)8,
                            Nombre = "VICHADA",
                            PaisId = 1,
                            UsuarioCreadorId = 1
                        });
                });

            modelBuilder.Entity("DCO.Dominio.Entidades.DCO_Lista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificado")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("DCO_Listas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "CARGOSEMPLEADOS",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(3859),
                            Nombre = "CARGOS PARA EMPLEADOS",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "CAUSASEXTERNAS",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(3862),
                            Nombre = "CAUSAS EXTERNAS SALUD",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "ESPECIALIDAD",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(3864),
                            Nombre = "ESPECIALIDADES",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "NIVELESCOMPLEJIDAD",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(3866),
                            Nombre = "NIVELES DE COMPLEJIDAD EN SALUD",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "ESTADOANEXOS",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(3868),
                            Nombre = "ESTADOS DE LOS ANEXOS TÉCNICOS",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "SERVICIOS",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(3870),
                            Nombre = "SERVICIOS DE SALUD",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "SEXOBIOLOGICO",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(3871),
                            Nombre = "SEXO BIOLÓGICO",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "TIPOAFILIACION",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(3873),
                            Nombre = "TIPOS DE AFILIACIÓN EN SALUD",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "TIPOSIDENTIFICACION",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(3875),
                            Nombre = "TIPOS DE IDENTIFICACIÓN",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "TIPOREGIMEN",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(3877),
                            Nombre = "TIPOS DE REGIMEN EN SALUD",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 11,
                            Codigo = "TIPOSTRIAGE",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(3878),
                            Nombre = "TIPOS DE TRIAGE",
                            UsuarioCreadorId = 1
                        });
                });

            modelBuilder.Entity("DCO.Dominio.Entidades.DCO_ListaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificado")
                        .HasColumnType("datetime");

                    b.Property<int>("ListaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ListaId", "Codigo")
                        .IsUnique();

                    b.ToTable("DCO_ListasDetalles");
                });

            modelBuilder.Entity("DCO.Dominio.Entidades.DCO_Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificado")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId", "Codigo")
                        .IsUnique();

                    b.ToTable("DCO_Municipio");
                });

            modelBuilder.Entity("DCO.Dominio.Entidades.DCO_Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificado")
                        .HasColumnType("datetime");

                    b.Property<short>("Indicativo")
                        .HasColumnType("smallint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("DCO_Pais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "COL",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2025, 11, 22, 13, 19, 16, 527, DateTimeKind.Local).AddTicks(4052),
                            Indicativo = (short)57,
                            Nombre = "COLOMBIA",
                            UsuarioCreadorId = 1
                        });
                });

            modelBuilder.Entity("DCO.Dominio.Entidades.DCO_Barrio", b =>
                {
                    b.HasOne("DCO.Dominio.Entidades.DCO_Municipio", "Municipio")
                        .WithMany("Barrios")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("DCO.Dominio.Entidades.DCO_DatoConstante", b =>
                {
                    b.HasOne("DCO.Dominio.Entidades.DCO_Lista", "Lista")
                        .WithMany("DatosConstantes")
                        .HasForeignKey("ListaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lista");
                });

            modelBuilder.Entity("DCO.Dominio.Entidades.DCO_DatoConstanteDetalle", b =>
                {
                    b.HasOne("DCO.Dominio.Entidades.DCO_DatoConstante", "DatoConstante")
                        .WithMany("DatosConstantesDetalles")
                        .HasForeignKey("DatoConstanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DCO.Dominio.Entidades.DCO_ListaDetalle", "ListaDetalle")
                        .WithMany("DatosConstantesDetalles")
                        .HasForeignKey("ListaDetalleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatoConstante");

                    b.Navigation("ListaDetalle");
                });

            modelBuilder.Entity("DCO.Dominio.Entidades.DCO_Departamento", b =>
                {
                    b.HasOne("DCO.Dominio.Entidades.DCO_Pais", "Pais")
                        .WithMany("Departamentos")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("DCO.Dominio.Entidades.DCO_ListaDetalle", b =>
                {
                    b.HasOne("DCO.Dominio.Entidades.DCO_Lista", "Lista")
                        .WithMany("ListasDetalles")
                        .HasForeignKey("ListaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lista");
                });

            modelBuilder.Entity("DCO.Dominio.Entidades.DCO_Municipio", b =>
                {
                    b.HasOne("DCO.Dominio.Entidades.DCO_Departamento", "Departamento")
                        .WithMany("Municipios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("DCO.Dominio.Entidades.DCO_DatoConstante", b =>
                {
                    b.Navigation("DatosConstantesDetalles");
                });

            modelBuilder.Entity("DCO.Dominio.Entidades.DCO_Departamento", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("DCO.Dominio.Entidades.DCO_Lista", b =>
                {
                    b.Navigation("DatosConstantes");

                    b.Navigation("ListasDetalles");
                });

            modelBuilder.Entity("DCO.Dominio.Entidades.DCO_ListaDetalle", b =>
                {
                    b.Navigation("DatosConstantesDetalles");
                });

            modelBuilder.Entity("DCO.Dominio.Entidades.DCO_Municipio", b =>
                {
                    b.Navigation("Barrios");
                });

            modelBuilder.Entity("DCO.Dominio.Entidades.DCO_Pais", b =>
                {
                    b.Navigation("Departamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
