@ApiDCO.DatosComunes_HostAddress = http://localhost:5013

//GET {{ApiDCO_HostAddress}}/weatherforecast/
GET {{ApiDCO.DatosComunes_HostAddress}}/Api/datoconstante/
Accept: application/json

###

GET {{ApiDCO.DatosComunes_HostAddress}}/Api/lista/
Accept: application/json

###